version: '3.4'

services:
  mc2.crudtest.presentation.server:
    image: ${DOCKER_REGISTRY-}mc2crudtestpresentationserver
    build:
      context: .
      dockerfile: Mc2.CrudTest.Presentation\Server\Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "TestPassw0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
